version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - gocyclo
    - gosec
    - unconvert
    - dupl
    - prealloc
    - nolintlint
    - revive
    - unparam
