run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - gocyclo
    - gosec
    - unconvert
    - dupl
    - prealloc
    - revive
    - unparam
  disable:
    - nolintlint  # Disabled to allow defensive nolint directives
