run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gosec
    - unconvert
    - prealloc
    - revive
  disable:
    - nolintlint  # Disabled to allow defensive nolint directives
    - dupl        # Disabled to allow similar test patterns
    - gocritic    # Disabled to reduce noise for now
    - gocyclo     # Disabled to reduce noise for now
    - unparam     # Disabled to reduce noise for now

linters-settings:
  govet:
    enable:
      - shadow
