version: "2"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - ctfify
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - gocyclo
    - gosec
    - unconvert
    - dupl
    - prealloc
    - nolintlint
    - revive
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  misspell:
    locale: US

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  gosec:
    excludes:
      - G404 # Use of weak random number generator

  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
      - name: unreachable-code
        severity: warning
      - name: unused-parameter
        severity: warning

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocritic

    # Exclude known issues in legacy code
    - path: internal/gzcli/gzapi/
      linters:
        - gosec

  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 3

  # Show only new issues
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

