version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: gzcli
    binary: gzcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/dimasma0305/gzcli/cmd.Version={{.Version}}
      - -X github.com/dimasma0305/gzcli/cmd.BuildTime={{.Date}}
      - -X github.com/dimasma0305/gzcli/cmd.GitCommit={{.Commit}}
    mod_timestamp: '{{ .CommitTimestamp }}'

universal_binaries:
  - id: gzcli-darwin
    replace: true

# UPX compression for smaller binaries
# Note: UPX may trigger false positives in some antivirus software
# and adds ~10-20ms to startup time, but reduces size by 50-70%
upx:
  - enabled: true
    goos: [linux, windows]
    goarch: [amd64, arm64, arm, "386"]
    # Compression level: 1-9 (1=fast, 9=best compression)
    # Level 9 gives best compression but takes longer to build
    compress: best
    # Level 1-9 numeric value (9 = best compression)
    lzma: true

archives:
  - id: gzcli-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Refactors'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 4
    - title: 'Other'
      order: 999

release:
  github:
    owner: dimasma0305
    name: gzcli
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} v{{.Version}}"

# Homebrew tap configuration - commented out until repository is created
# To enable: create the repository github.com/dimasma0305/homebrew-tap and uncomment below
# brews:
#   - repository:
#       owner: dimasma0305
#       name: homebrew-tap
#     directory: Formula
#     homepage: "https://github.com/dimasma0305/gzcli"
#     description: "High-performance command-line interface for GZ::CTF operations"
#     license: "MIT"
#     test: |
#       system "#{bin}/gzcli", "--version"
#     install: |
#       bin.install "gzcli"
#       bash_completion.install "completions/gzcli.bash" => "gzcli"
#       zsh_completion.install "completions/_gzcli" => "_gzcli"
#       fish_completion.install "completions/gzcli.fish"
