name: '{{.Workspace}}'

services:
  gzcli:
    build:
      context: ./manager
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "{{.RootFolder}}:{{.RootFolder}}"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "WORKDIR={{.RootFolder}}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # service ports
      - "traefik.http.services.gzcli-${WORKSPACE}.loadbalancer.server.port=3000"

      # https router
      - "traefik.http.routers.gzcli-${WORKSPACE}-https.rule=Host(`gzcli.${PUBLIC_ENTRY}`)"
      - "traefik.http.routers.gzcli-${WORKSPACE}-https.entrypoints=websecure"
      - "traefik.http.routers.gzcli-${WORKSPACE}-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gzcli-${WORKSPACE}-https.service=gzcli-${WORKSPACE}"
    networks:
      traefik:


networks:
  traefik:
    external: true
